//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace America_Virtual.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AmericaVirtualEntities : DbContext
    {
        public AmericaVirtualEntities()
            : base("name=AmericaVirtualEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Localidad> Localidad { get; set; }
        public virtual DbSet<Localidades> Localidades { get; set; }
        public virtual DbSet<Partidos> Partidos { get; set; }
        public virtual DbSet<Provincia> Provincia { get; set; }
        public virtual DbSet<Provincias> Provincias { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
