//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace America_Virtual.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partidos()
        {
            this.Localidades = new HashSet<Localidades>();
        }
    
        public System.Guid ORID { get; set; }
        public string Descripcion { get; set; }
        public string CODE { get; set; }
        public System.Guid IdProvincia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Localidades> Localidades { get; set; }
        public virtual Provincias Provincias { get; set; }
    }
}
